#functions:
def investigateWindow():
    print("You stand up. The window is just above your eyesight, so you have to stand on a box you found in the corner.")
    print("The box is just enough to boost you the extra 5 inches you need to see out the window.")
    print("You are momentarily blinded by the light, having been long in the dark. You see a bustling street, from what you can gather as about 10 or so feet off the ground.")
    print("The street is full of vendors, and below your window you can see a heavy wooden door guarded by two soldiers.")

def after_the_window_1():
    print("Suddenly, a light shines behind you.")
    print("A guard has come into your room and lit a torch. You can now see you're in a jail cell.")
    print("The guard says,")
    print("'Hey you! Get away from the window! You're coming with me.'")
    print("He ties your hands behind your back, and leads you outside your cell. You can see two exits: the one the guard leads you towards now, and another at the other end of the hall.")
    print("What do you do?")
    print("1. Go with the guard")
    print("2. Run for the other exit")

#Checking functions 
def checkOption(option):
    if option.isnumeric:
        pass
    else:
        print("Invalid option. Please insert a number.") 

def checkAttempt(attempt):
    if attempt.isnumeric:
        pass
    else: 
        print("Answer was invalid. Please enter a number.") 

#Health
def printHealth(health):
    print(f"Health: {health}") 

def checkHealth(health):
    if health == 0:
        print("You have taken too much damage.")
        print("You have died.")
    else:
        pass

#Run counter
run_list = []
def printRuns():
    for i in range(len(run_list)):
        if run_list[i] == 1:
            print(f"Run {i + 1} was a win")
        elif run_list[i] == 0:
            print(f"Run {i + 1} was a loss")



#Program
def main():
    check = True 
    while check == True:
        health = 100
        print("Welcome to the choose your own adventure!")
        quit_option = input("If you would like to quit, enter 'quit' into the terminal, if not, hit 'enter': ").lower().strip()
        if quit_option == "quit":
            check = False
        else:
            print("You awake in a dark room. The air smells musty, and you feel water dripping onto you from what you assume is the ceiling. A faint light is coming through a small, slit window above your head.")
            print(f"Health: {health}.")
            print("What do you do first?")
            print("1. Investigate the water.")
            print("2. Investigate the window.")
            option = input("Which number do you choose: ")
            checkOption(option)
            if int(option) == 1:
                print("You look up to the ceiling. A water droplet falls in your eye. Take one damage.")
                health = health - 1
                checkHealth(health) 
                printHealth(health) 
                print("You notice that the water seems to be coming from a crack in the ceiling.")
                print("You now investigate the window.")
                investigateWindow()
                after_the_window_1() 
                option = input("Which do you choose: ")
                checkOption(option)
                if int(option) == 1:
                    print("The guard leads you down to the main floor of the prison.")
                    print("He says,")
                    print("'There's someone here to see you.'")
                    attempt = input("Choose a number between one and ten: ")
                    checkAttempt(attempt)
                    if int(attempt) % 2 == 1:
                        print("You hear the guard mutter something, but don't catch the words.")
                    elif int(attempt) % 2 == 0:
                        print("You hear him mutter under his breath,")
                        print("Slimy mage. Shouldn't have done magic if they knew it was outlawed.")
                    print("He leads you into a room, where a mysterious stranger is seated on the other side of a table.")
                    attempt = input("Choose a number between one and ten: ")
                    checkAttempt(attempt)
                    if int(attempt) < 5:
                        print("He wears a dark cloak with the hood up, so you are unable to see his face.")
                        print("The man looks to the guard and says,")
                    elif int(attempt) > 5:
                        print("He wears a dark cloak with the hood up to conceal his face, but as the guard brings the torch into the room, you see a face you haven't seen in a long time.")
                        print("It's Merlin!")
                        print("He looks into your eyes, and you suddenly have the feeling that you shouldn't reveal that you know him.")
                        print("Merlin looks to the guard and says,")
                    print("'We no longer need your assistance.'")
                    print("The guard then turns and walks out of the room, and you hear the telltale sound of the lock clicking.")
                    print("Left alone in the room, he says,")
                    print("'You are in great danger. You must come with me now, or something bad will happen. I can't tell you what, but know it will be terrible.'")
                    print("What do you do?")
                    print("1. Go with him")
                    print("2. Stay behind")
                    option = input("Which do you choose: ")
                    checkOption(option)
                    if int(option) == 1:
                        print("You take his outstrechted hand, and feel a warm tingle in your stomach.")
                        print("The last you see of the prision is a bright flash of light, and then you materialize in a castle.")
                        print("As soon as you're there, you feel that something's off.")
                        print("Your companion looks back at you and smiles sinisterly,")
                        print("I never thought you'd fall for it. Too bad, I guess! For you, not me.")
                        print("HAHAHAHAHAH!")
                        print("The last thing you feel as you watch your body disintegrate is regret, and a vague sense of fear.")
                        print("You don't know what this stranger plans to do with you, but you know it's not good.")
                        print("You have failed.")
                        run_list.append(0)
                        printRuns()
                    elif int(option) == 2:
                        print("He frowns.")
                        print("This is your last chance, puny human. I'm being very generous.")
                        print("Do you go with him?")
                        print("1. Yes")
                        print("2. No")
                        option = input("What do you choose: ")
                        checkOption(option)
                        if int(option) == 1:
                            print("You take his outstrechted hand, and feel a warm tingle in your stomach.")
                            print("The last you see of the prision is a bright flash of light, and then you materialize in a castle.")
                            print("As soon as you're there, you feel that something's off.")
                            print("Your companion looks back at you and smiles sinisterly,")
                            print("I never thought you'd fall for it. Too bad, I guess! For you, not me.")
                            print("HAHAHAHAHAH!")
                            print("The last thing you feel as you watch your body disintegrate is regret, and a vague sense of fear.")
                            print("You don't know what this stranger plans to do with you, but you know it's not good.")
                            print("You have failed.")
                            run_list.append(0)
                            printRuns()
                        if int(option) == 2:
                            print("You shake your head,")
                            print("He doesn't seem shocked that you didn't go with him, almost as if he expected this.")
                            print("You bang on the door, alearting the guards.")
                            print("As they rush in the room, you hear a bang.")                        
                            health = health - 20
                            checkHealth(health) 
                            printHealth(health) 
                            print("As guards come rushing into the room, you turn and see that the stranger has caused an explosion, and is standing in the subsequent smoke.")
                            print("What do you do?")
                            print("1. Hide under the table")
                            print("2. Run outside")
                            option = input("Which do you choose: ")
                            checkOption(option)
                            if int(option) == 1:
                                print("You dive under the table, and hear the sounds of a fight starting around you.")
                                print("The stranger seems to be holding his own, as you see guards falling from you vantage point under the table.")
                                print("Eventually, the sounds of conflict subside, and you feel a chill come into the room.")
                                print("The stranger speaks, though he doesn't look at you:")
                                print("Little mage, this is your last chance. Come with me willingly, and no harm will come to you.")
                                print("What do you do?")
                                print("1. Run for the door")
                                print("2. Go with him")
                                option = input("Which do you choose: ")
                                checkOption(option)
                                if int(option) == 1:
                                    print("You run for the door, and you hear the mage curse behind you.")
                                    attempt = input("Choose a number between one and ten: ")
                                    checkAttempt(attempt)
                                    if int(attempt) % 2 == 1:
                                        print("You dodge the magic he throws at you, and run to the exit.")
                                        print("Since you left most of the guards incapacitated in the room, there is no one to stop your excape.")
                                        print("Once you reach the doors, and breath in fresh air, you know that you are safe.")
                                        print("You have succeeded!")
                                        run_list.append(1)
                                        printRuns() 
                                    elif int(attempt) % 2 == 0:
                                        print("As you run for the door, you are hit with magic.")
                                        print("'A pitiful attempt. No matter.'")
                                        print("The mage says, as he snaps his fingers.")
                                        print("You feel your body begin to disintagrate, and you know no amount of fighting will save you.")
                                        print("You have failed.")
                                        run_list.append(0)
                                        printRuns()
                            elif int(option) == 2:
                                print("As guards rush into the room, you run to the door.")
                                print("They are far too concerned with the dark mage in the room to notice you flee for the exit.")
                                print("As you run through the prision, you see more and more guards running to the room you were in to deal with the mage.")
                                print("This means that no one is there to stop your escape once you reach the doors, and as you breath in the fresh air, you know no one will find you.")
                                print("You have succeeded!")
                                run_list.append(1)
                                printRuns()
                elif int(option) == 2:
                    print("You surprise the guard with a kick to the shin, and make a run for the other exit.")
                    print("As you run for the other exit, another guard comes up from the stairs you now see were behind the door. What do you do?")
                    print("1. Stop and let the guard catch you")
                    print("2. Fight the guard")
                    option = input("Which do you choose: ")
                    checkOption(option)
                    if int(option) == 1:
                        print("The guard immidiatly pushes you to the floor.")
                        health = health - 10 
                        checkHealth(health) 
                        printHealth(health) 
                        print("You stumble as he hauls you up, shouting to the other guard, alerting him of your capture.")
                        print("The first guard regards you suspiciously, saying")
                        print("You'll have a longer sentence for that, grub.")
                        print("He roughly grabs your shoulder, and leads you to the first floor of the prision.")
                        print("The guard leads you down to the main floor of the prison.")
                        print("He says,")
                        print("'There's someone here to see you.'")
                        attempt = input("Choose a number between one and ten: ")
                        checkAttempt(attempt)
                        if int(attempt) % 2 == 1:
                            print("You hear the guard mutter something, but don't catch the words.")
                        elif int(attempt) % 2 == 0:
                            print("You hear him mutter under his breath,")
                            print("Slimy mage. Shouldn't have done magic if they knew it was outlawed.")
                        print("He leads you into a room, where a mysterious stranger is seated on the other side of a table.")
                        attempt = input("Choose a number between one and ten: ")
                        checkAttempt(attempt)
                        if int(attempt) < 5:
                            print("He wears a dark cloak with the hood up, so you are unable to see his face.")
                            print("The man looks to the guard and says,")
                        elif int(attempt) > 5:
                            print("He wears a dark cloak with the hood up to conceal his face, but as the guard brings the torch into the room, you see a face you haven't seen in a long time.")
                            print("It's Merlin!")
                            print("He looks into your eyes, and you suddenly have the feeling that you shouldn't reveal that you know him.")
                            print("Merlin looks to the guard and says,")
                        print("'We no longer need your assistance.'")
                        print("The guard then turns and walks out of the room, and you hear the telltale sound of the lock clicking.")
                        print("Left alone in the room, he says,")
                        print("'You are in great danger. You must come with me now, or something bad will happen. I can't tell you what, but know it will be terrible.'")
                        print("What do you do?")
                        print("1. Go with him")
                        print("2. Stay behind")
                        option = input("Which do you choose: ")
                        checkOption(option)
                        if int(option) == 1:
                            print("You take his outstrechted hand, and feel a warm tingle in your stomach.")
                            print("The last you see of the prision is a bright flash of light, and then you materialize in a castle.")
                            print("As soon as you're there, you feel that something's off.")
                            print("Your companion looks back at you and smiles sinisterly,")
                            print("I never thought you'd fall for it. Too bad, I guess! For you, not me.")
                            print("HAHAHAHAHAH!")
                            print("The last thing you feel as you watch your body disintegrate is regret, and a vague sense of fear.")
                            print("You don't know what this stranger plans to do with you, but you know it's not good.")
                            print("You have failed.")
                            run_list.append(0)
                            printRuns()
                        elif int(option) == 2:
                            print("He frowns.")
                            print("This is your last chance, puny human. I'm being very generous.")
                            print("Do you go with him?")
                            print("1. Yes")
                            print("2. No")
                            option = input("What do you choose: ")
                            checkOption(option)
                            if int(option) == 1:
                                print("You take his outstrechted hand, and feel a warm tingle in your stomach.")
                                print("The last you see of the prision is a bright flash of light, and then you materialize in a castle.")
                                print("As soon as you're there, you feel that something's off.")
                                print("Your companion looks back at you and smiles sinisterly,")
                                print("I never thought you'd fall for it. Too bad, I guess! For you, not me.")
                                print("HAHAHAHAHAH!")
                                print("The last thing you feel as you watch your body disintegrate is regret, and a vague sense of fear.")
                                print("You don't know what this stranger plans to do with you, but you know it's not good.")
                                print("You have failed.")
                                run_list.append(0)
                                printRuns()
                            elif int(option) == 2:
                                print("You shake your head,")
                                print("He doesn't seem shocked that you didn't go with him, almost as if he expected this.")
                                print("You bang on the door, alearting the guards.")
                                print("As they rush in the room, you hear a bang.")                        
                                health = health - 10
                                checkHealth(health) 
                                printHealth(health) 
                                print("As guards come rushing into the room, you turn and see that the stranger has caused an explosion, and is standing in the subsequent smoke.")
                                print("What do you do?")
                                print("1. Hide under the table")
                                print("2. Run outside")
                                option = input("Which do you choose: ")
                                checkOption(option)
                                if int(option) == 1:
                                    print("You dive under the table, and hear the sounds of a fight starting around you.")
                                    print("The stranger seems to be holding his own, as you see guards falling from you vantage point under the table.")
                                    print("Eventually, the sounds of conflict subside, and you feel a chill come into the room.")
                                    print("The stranger speaks, though he doesn't look at you:")
                                    print("Little mage, this is your last chance. Come with me willingly, and no harm will come to you.")
                                    print("What do you do?")
                                    print("1. Run for the door")
                                    print("2. Go with him")
                                    if int(option) == 1:
                                        print("You run for the door, and you hear the mage curse behind you.")
                                        attempt = input("Choose a number between one and ten: ")
                                        checkAttempt(attempt)
                                        if int(attempt) % 2 == 1:
                                            print("You dodge the magic he throws at you, and run to the exit.")
                                            print("Since you left most of the guards incapacitated in the room, there is no one to stop your excape.")
                                            print("Once you reach the doors, and breath in fresh air, you know that you are safe.")
                                            print("You have succeeded!")
                                            run_list.append(1)
                                            printRuns()
                                        elif int(attempt) % 2 == 0:
                                            print("As you run for the door, you are hit with magic.")
                                            print("'A pitiful attempt. No matter.'")
                                            print("The mage says, as he snaps his fingers.")
                                            print("You feel your body begin to disintagrate, and you know no amount of fighting will save you.")
                                            print("You have failed.")
                                            run_list.append(0)
                                            printRuns() 
                                    elif int(option) == 2:
                                        print("As guards rush into the room, you run to the door.")
                                        print("They are far too concerned with the dark mage in the room to notice you flee for the exit.")
                                        print("As you run through the prision, you see more and more guards running to the room you were in to deal with the mage.")
                                        print("This means that no one is there to stop your escape once you reach the doors, and as you breath in the fresh air, you know no one will find you.")
                                        print("You have succeeded!")
                                        run_list.append(1)
                                        printRuns()
                                elif int(option) == 2:
                                    print("As guards rush into the room, you run to the door.")
                                    print("They are far too concerned with the dark mage in the room to notice you flee for the exit.")
                                    print("As you run through the prision, you see more and more guards running to the room you were in to deal with the mage.")
                                    print("This means that no one is there to stop your escape once you reach the doors, and as you breath in the fresh air, you know no one will find you.")
                                    print("You have succeeded!")
                                    run_list.append(1)
                                    printRuns()
                    elif int(option) == 2:
                        print("You attack the guard by attempting to kick him.")
                        print("However, the guard heard you coming, and was prepared.")
                        print("He swings at you with his sword.")
                        attempt = input("Choose a number from one to ten: ")
                        checkAttempt(attempt)
                        if int(attempt) % 2 == 0:
                            print("You dodge the guard, and back away. Using your agility, you sneak around him and run down the stairs.")
                            print("You hear more shouting now, undobtedly the two guards sounding the alarm. You need to make it down the stairs fast.")
                            attempt = input("Choose a number between one and ten:")
                            if int(attempt) > 5:
                                print("As you make your way down the stairs, you trip.")
                                print("You then hear many voices coming up this same staircase.")
                                print("You try to get to your feet, but it's no use.")
                                print("The guards come rushing up the stiars, and together, they overpower your attempts to fight back.")
                                print("As they drag you back to your cell, you know you'll never get out now.")
                                print("You have failed.")
                                run_list.append(0)
                                printRuns()
                            elif int(attempt) < 5:
                                print("You stumble once or twice, but make it to the ground floor unscathed.")
                                print("Using a knife you find in a drawer, you free yourself from your bonds.")
                                print("As you rush towards the exit, you see the two soldiers you saw from your window running at you.")
                                print("What do you do?")
                                print("1. Fight them with your knife")
                                print("2. Slide beneath their feet")
                                option = input("what do you choose?")
                                checkOption(option)
                                if int(option) == 1:
                                    print("They come at you with their swords, and you try to block them with your knife.")
                                    print("Unfortunatly, they quickly fling it across the room and overpower you.")
                                    print("As they drag you back to your cell, you know you'll never escape now.")
                                    print("You have failed.")
                                    run_list.append(0)
                                    printRuns()
                                elif int(option) == 2:
                                    print("You drop, and slide beneath their feet, throwing them off for just enough time for you to run out the door.")
                                    print("As you lose them in the crowd, you breath the fresh air and feel alive once more.")
                                    print("You have succeeded!!!!")
                                    run_list.append(1)
                                    printRuns()
                        elif int(attempt) % 2 == 1:
                            print("You attempt to dodge the guard, but his sword slices deep into your shoulder.")
                            health = 10
                            checkHealth(health) 
                            printHealth(health) 
                            print("The other guard comes up behind you, and wrestles you back into your cell.")
                            print("He says,")
                            print("'Now you'll never be free. WAHAHAHA!'")
                            print("The cut is very deep, and as the water from the ceiling drips into it, making it sting, you know it will be infected by morning.")
                            print("You have failed.")
                            run_list.append(0)
                            printRuns()

#_____________Second option, start____________________________________________________# 

            elif int(option) == 2: 
                investigateWindow()
                after_the_window_1() 
                option = input("Which do you choose: ")
                checkOption(option)
                if int(option) == 1:
                    print("The guard leads you down to the main floor of the prison.")
                    print("He says,")
                    print("'There's someone here to see you.'")
                    attempt = input("Choose a number between one and ten: ")
                    checkAttempt(attempt)
                    if int(attempt) % 2 == 1:
                        print("You hear the guard mutter something, but don't catch the words.")
                    elif int(attempt) % 2 == 0:
                        print("You hear him mutter under his breath,")
                        print("Slimy mage. Shouldn't have done magic if they knew it was outlawed.")
                    print("He leads you into a room, where a mysterious stranger is seated on the other side of a table.")
                    attempt = input("Choose a number between one and ten: ")
                    if int(attempt) < 5:
                        print("He wears a dark cloak with the hood up, so you are unable to see his face.")
                        print("The man looks to the guard and says,")
                    elif int(attempt) > 5:
                        print("He wears a dark cloak with the hood up to conceal his face, but as the guard brings the torch into the room, you see a face you haven't seen in a long time.")
                        print("It's Merlin!")
                        print("He looks into your eyes, and you suddenly have the feeling that you shouldn't reveal that you know him.")
                        print("Merlin looks to the guard and says,")
                    print("'We no longer need your assistance.'")
                    print("The guard then turns and walks out of the room, and you hear the telltale sound of the lock clicking.")
                    print("Left alone in the room, he says,")
                    print("'You are in great danger. You must come with me now, or something bad will happen. I can't tell you what, but know it will be terrible.'")
                    print("What do you do?")
                    print("1. Go with him")
                    print("2. Stay behind")
                    option = input("Which do you choose: ")
                    checkOption(option)
                    if int(option) == 1:
                        print("You take his outstrechted hand, and feel a warm tingle in your stomach.")
                        print("The last you see of the prision is a bright flash of light, and then you materialize in a castle.")
                        print("As soon as you're there, you feel that something's off.")
                        print("Your companion looks back at you and smiles sinisterly,")
                        print("I never thought you'd fall for it. Too bad, I guess! For you, not me.")
                        print("HAHAHAHAHAH!")
                        print("The last thing you feel as you watch your body disintegrate is regret, and a vague sense of fear.")
                        print("You don't know what this stranger plans to do with you, but you know it's not good.")
                        print("You have failed.")
                        run_list.append(0)
                        printRuns()
                    elif int(option) == 2:
                        print("He frowns.")
                        print("This is your last chance, puny human. I'm being very generous.")
                        print("Do you go with him?")
                        print("1. Yes")
                        print("2. No")
                        option = input("What do you choose: ")
                        checkOption(option)
                        if int(option) == 1:
                            print("You take his outstrechted hand, and feel a warm tingle in your stomach.")
                            print("The last you see of the prision is a bright flash of light, and then you materialize in a castle.")
                            print("As soon as you're there, you feel that something's off.")
                            print("Your companion looks back at you and smiles sinisterly,")
                            print("I never thought you'd fall for it. Too bad, I guess! For you, not me.")
                            print("HAHAHAHAHAH!")
                            print("The last thing you feel as you watch your body disintegrate is regret, and a vague sense of fear.")
                            print("You don't know what this stranger plans to do with you, but you know it's not good.")
                            print("You have failed.")
                            run_list.append(0)
                            printRuns() 
                        elif int(option) == 2:
                            print("You shake your head,")
                            print("He doesn't seem shocked that you didn't go with him, almost as if he expected this.")
                            print("You bang on the door, alearting the guards.")
                            print("As they rush in the room, you hear a bang.")                        
                            health = health - 10
                            checkHealth(health) 
                            printHealth(health) 
                            print("As guards come rushing into the room, you turn and see that the stranger has caused an explosion, and is standing in the subsequent smoke.")
                            print("What do you do?")
                            print("1. Hide under the table")
                            print("2. Run outside")
                            option = input("Which do you choose: ")
                            checkOption(option)
                            if int(option) == 1:
                                print("You dive under the table, and hear the sounds of a fight starting around you.")
                                print("The stranger seems to be holding his own, as you see guards falling from you vantage point under the table.")
                                print("Eventually, the sounds of conflict subside, and you feel a chill come into the room.")
                                print("The stranger speaks, though he doesn't look at you:")
                                print("Little mage, this is your last chance. Come with me willingly, and no harm will come to you.")
                                print("What do you do?")
                                print("1. Run for the door")
                                print("2. Go with him")
                                option = input("Which do you choose: ")
                                checkOption(option)
                                if int(option) == 1:
                                    print("You run for the door, and you hear the mage curse behind you.")
                                    attempt = input("Choose a number between one and ten: ")
                                    checkAttempt(attempt)
                                    if int(attempt) % 2 == 1:
                                        print("You dodge the magic he throws at you, and run to the exit.")
                                        print("Since you left most of the guards incapacitated in the room, there is no one to stop your excape.")
                                        print("Once you reach the doors, and breath in fresh air, you know that you are safe.")
                                        print("You have succeeded!")
                                        run_list.append(1)
                                        printRuns()
                                    elif int(attempt) % 2 == 0:
                                        print("As you run for the door, you are hit with magic.")
                                        print("'A pitiful attempt. No matter.'")
                                        print("The mage says, as he snaps his fingers.")
                                        print("You feel your body begin to disintagrate, and you know no amount of fighting will save you.")
                                        print("You have failed.")
                                        run_list.append(0) 
                                        printRuns()
                                elif int(option) == 2:
                                    print("As guards rush into the room, you run to the door.")
                                    print("They are far too concerned with the dark mage in the room to notice you flee for the exit.")
                                    print("As you run through the prision, you see more and more guards running to the room you were in to deal with the mage.")
                                    print("This means that no one is there to stop your escape once you reach the doors, and as you breath in the fresh air, you know no one will find you.")
                                    print("You have succeeded!")
                                    run_list.append(1)
                                    printRuns() 
                            elif int(option) == 2:
                                print("As guards rush into the room, you run to the door.")
                                print("They are far too concerned with the dark mage in the room to notice you flee for the exit.")
                                print("As you run through the prision, you see more and more guards running to the room you were in to deal with the mage.")
                                print("This means that no one is there to stop your escape once you reach the doors, and as you breath in the fresh air, you know no one will find you.")
                                print("You have succeeded!")
                                run_list.append(1)
                                printRuns()
                elif int(option) == 2:
                    print("You surprise the guard with a kick to the shin, and make a run for the other exit.")
                    print("As you run for the other exit, another guard comes up from the stairs you now see were behind the door. What do you do?")
                    print("1. Stop and let the guard catch you")
                    print("2. Fight the guard")
                    option = input("Which do you choose: ")
                    checkOption(option)
                    if int(option) == 1:
                        print("The guard immidiatly pushes you to the floor.")
                        health = health - 10 
                        checkHealth(health) 
                        printHealth(health) 
                        print("You stumble as he hauls you up, shouting to the other guard, alerting him of your capture.")
                        print("The first guard regards you suspiciously, saying")
                        print("You'll have a longer sentence for that, grub.")
                        print("He roughly grabs your shoulder, and leads you to the first floor of the prision.")
                        print("The guard leads you down to the main floor of the prison.")
                        print("He says,")
                        print("'There's someone here to see you.'")
                        attempt = input("Choose a number between one and ten: ")
                        checkAttempt(attempt)
                        if int(attempt) % 2 == 1:
                            print("You hear the guard mutter something, but don't catch the words.")
                        elif int(attempt) % 2 == 0:
                            print("You hear him mutter under his breath,")
                            print("Slimy mage. Shouldn't have done magic if they knew it was outlawed.")
                        print("He leads you into a room, where a mysterious stranger is seated on the other side of a table.")
                        attempt = input("Choose a number between one and ten: ")
                        checkAttempt(attempt)
                        if int(attempt) < 5:
                            print("He wears a dark cloak with the hood up, so you are unable to see his face.")
                            print("The man looks to the guard and says,")
                        elif int(attempt) > 5:
                            print("He wears a dark cloak with the hood up to conceal his face, but as the guard brings the torch into the room, you see a face you haven't seen in a long time.")
                            print("It's Merlin!")
                            print("He looks into your eyes, and you suddenly have the feeling that you shouldn't reveal that you know him.")
                            print("Merlin looks to the guard and says,")
                        print("'We no longer need your assistance.'")
                        print("The guard then turns and walks out of the room, and you hear the telltale sound of the lock clicking.")
                        print("Left alone in the room, he says,")
                        print("'You are in great danger. You must come with me now, or something bad will happen. I can't tell you what, but know it will be terrible.'")
                        print("What do you do?")
                        print("1. Go with him")
                        print("2. Stay behind")
                        option = input("Which do you choose: ")
                        checkOption(option)
                        if int(option) == 1:
                            print("You take his outstrechted hand, and feel a warm tingle in your stomach.")
                            print("The last you see of the prision is a bright flash of light, and then you materialize in a castle.")
                            print("As soon as you're there, you feel that something's off.")
                            print("Your companion looks back at you and smiles sinisterly,")
                            print("I never thought you'd fall for it. Too bad, I guess! For you, not me.")
                            print("HAHAHAHAHAH!")
                            print("The last thing you feel as you watch your body disintegrate is regret, and a vague sense of fear.")
                            print("You don't know what this stranger plans to do with you, but you know it's not good.")
                            print("You have failed.")
                            run_list.append(0)
                            printRuns()
                        elif int(option) == 2:
                            print("He frowns.")
                            print("This is your last chance, puny human. I'm being very generous.")
                            print("Do you go with him?")
                            print("1. Yes")
                            print("2. No")
                            option = input("What do you choose: ")
                            checkOption(option)
                            if int(option) == 1:
                                print("You take his outstrechted hand, and feel a warm tingle in your stomach.")
                                print("The last you see of the prision is a bright flash of light, and then you materialize in a castle.")
                                print("As soon as you're there, you feel that something's off.")
                                print("Your companion looks back at you and smiles sinisterly,")
                                print("I never thought you'd fall for it. Too bad, I guess! For you, not me.")
                                print("HAHAHAHAHAH!")
                                print("The last thing you feel as you watch your body disintegrate is regret, and a vague sense of fear.")
                                print("You don't know what this stranger plans to do with you, but you know it's not good.")
                                print("You have failed.")
                                run_list.append(0)
                                printRuns
                            elif int(option) == 2:
                                print("You shake your head,")
                                print("He doesn't seem shocked that you didn't go with him, almost as if he expected this.")
                                print("You bang on the door, alearting the guards.")
                                print("As they rush in the room, you hear a bang.")                        
                                health = health - 10
                                checkHealth(health) 
                                printHealth(health)
                                print("As guards come rushing into the room, you turn and see that the stranger has caused an explosion, and is standing in the subsequent smoke.")
                                print("What do you do?")
                                print("1. Hide under the table")
                                print("2. Run outside")
                                option = input("Which do you choose: ")
                                checkOption(option)
                                if int(option) == 1:
                                    print("You dive under the table, and hear the sounds of a fight starting around you.")
                                    print("The stranger seems to be holding his own, as you see guards falling from you vantage point under the table.")
                                    print("Eventually, the sounds of conflict subside, and you feel a chill come into the room.")
                                    print("The stranger speaks, though he doesn't look at you:")
                                    print("Little mage, this is your last chance. Come with me willingly, and no harm will come to you.")
                                    print("What do you do?")
                                    print("1. Run for the door")
                                    print("2. Go with him")
                                    if int(option) == 1:
                                        print("You run for the door, and you hear the mage curse behind you.")
                                        attempt = input("Choose a number between one and ten: ")
                                        checkAttempt(attempt)
                                        if int(attempt) % 2 == 1:
                                            print("You dodge the magic he throws at you, and run to the exit.")
                                            print("Since you left most of the guards incapacitated in the room, there is no one to stop your excape.")
                                            print("Once you reach the doors, and breath in fresh air, you know that you are safe.")
                                            print("You have succeeded!")
                                            run_list.append(1)
                                            printRuns()
                                        elif int(attempt) % 2 == 0:
                                            print("As you run for the door, you are hit with magic.")
                                            print("'A pitiful attempt. No matter.'")
                                            print("The mage says, as he snaps his fingers.")
                                            print("You feel your body begin to disintagrate, and you know no amount of fighting will save you.")
                                            print("You have failed.")
                                            run_list.append(0)
                                            printRuns()
                                    elif int(option) == 2:
                                        print("As guards rush into the room, you run to the door.")
                                        print("They are far too concerned with the dark mage in the room to notice you flee for the exit.")
                                        print("As you run through the prision, you see more and more guards running to the room you were in to deal with the mage.")
                                        print("This means that no one is there to stop your escape once you reach the doors, and as you breath in the fresh air, you know no one will find you.")
                                        print("You have succeeded!")
                                        run_list.append(1)
                                        printRuns()
                                elif int(option) == 2:
                                    print("As guards rush into the room, you run to the door.")
                                    print("They are far too concerned with the dark mage in the room to notice you flee for the exit.")
                                    print("As you run through the prision, you see more and more guards running to the room you were in to deal with the mage.")
                                    print("This means that no one is there to stop your escape once you reach the doors, and as you breath in the fresh air, you know no one will find you.")
                                    print("You have succeeded!")
                                    run_list.append(1)
                                    printRuns()
                    elif int(option) == 2:
                        print("You attack the guard by attempting to kick him.")
                        print("However, the guard heard you coming, and was prepared.")
                        print("He swings at you with his sword.")
                        attempt = input("Choose a number from one to ten: ")
                        checkAttempt(attempt)
                        if int(attempt) % 2 == 0:
                            print("You dodge the guard, and back away. Using your agility, you sneak around him and run down the stairs.")
                            print("You hear more shouting now, undobtedly the two guards sounding the alarm. You need to make it down the stairs fast.")
                            attempt = input("Choose a number between one and ten:")
                            checkAttempt(attempt)
                            if int(attempt) > 5:
                                print("As you make your way down the stairs, you trip.")
                                print("You then hear many voices coming up this same staircase.")
                                print("You try to get to your feet, but it's no use.")
                                print("The guards come rushing up the stiars, and together, they overpower your attempts to fight back.")
                                print("As they drag you back to your cell, you know you'll never get out now.")
                                print("You have failed.")
                                run_list.append(0)
                                printRuns()
                            elif int(attempt) < 5:
                                print("You stumble once or twice, but make it to the ground floor unscathed.")
                                print("Using a knife you find in a drawer, you free yourself from your bonds.")
                                print("As you rush towards the exit, you see the two soldiers you saw from your window running at you.")
                                print("What do you do?")
                                print("1. Fight them with your knife")
                                print("2. Slide beneath their feet")
                                option = input("what do you choose?")
                                checkOption(option)
                                if int(option) == 1:
                                    print("They come at you with their swords, and you try to block them with your knife.")
                                    print("Unfortunatly, they quickly fling it across the room and overpower you.")
                                    print("As they drag you back to your cell, you know you'll never escape now.")
                                    print("You have failed.")
                                    run_list.append(0)
                                    printRuns()
                                elif int(option) == 2:
                                    print("You drop, and slide beneath their feet, throwing them off for just enough time for you to run out the door.")
                                    print("As you lose them in the crowd, you breath the fresh air and feel alive once more.")
                                    print("You have succeeded!!!!")
                                    run_list.append(1)
                                    printRuns()
                        elif int(attempt) % 2 == 1:
                            print("You attempt to dodge the guard, but his sword slices deep into your shoulder.")
                            health = health - 70 
                            checkHealth(health) 
                            printHealth(health) 
                            print("The other guard comes up behind you, and wrestles you back into your cell.")
                            print("He says,")
                            print("'Now you'll never be free. WAHAHAHA!'")
                            print("The cut is very deep, and as the water from the ceiling drips into it, making it sting, you know it will be infected by morning.")
                            print("You have failed.")
                            run_list.append(0)
                            printRuns() 


#Actual program:
main() 